[[LCIO]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c422e271ba2f8cae8e7c6ddd60358dbb23b18e5"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "17cb36f2fa20cef6462eb8434fe23ed3a8b3cf2832c52022d103ede4812eb451"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.15.4+0/LCIO.v2.15.4.aarch64-linux-gnu-cxx03.tar.gz"
[[LCIO]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56da3017ced81766a6eea22666770c68dd58ef27"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "c40ece0c4bc6ccca3716f389bdbe3084f5ecfe5c69ad841c904c49902a970dbc"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.15.4+0/LCIO.v2.15.4.aarch64-linux-gnu-cxx11.tar.gz"
[[LCIO]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc0b414f0f2f71b8d8b885b58fd2fecaf9714fae"
libc = "musl"
os = "linux"

    [[LCIO.download]]
    sha256 = "0a52a335c8cd8430c652788b820b1c8236b596ccf30eaedab54b6587ea758b35"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.15.4+0/LCIO.v2.15.4.aarch64-linux-musl-cxx03.tar.gz"
[[LCIO]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cef845843057f2146ff2026cd63c6a6c614e4231"
libc = "musl"
os = "linux"

    [[LCIO.download]]
    sha256 = "3ee453cd6e1397a104b35fbe8ad928591f842c9674874bdb61f35a920af3ddad"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.15.4+0/LCIO.v2.15.4.aarch64-linux-musl-cxx11.tar.gz"
[[LCIO]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0098733007ee1b3d199ce95c2d9f60b1d8bc495"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "a577f36d2502a66a3206c4d07f7e9970f036603332ccc542d52c73c343ab7f2d"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.15.4+0/LCIO.v2.15.4.i686-linux-gnu-cxx03.tar.gz"
[[LCIO]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1877d6873bc431811d5e9b463d251a3d0b509134"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "7a2be09dc4ebf3932a68bbbe587864de2b4a380269e2f794a9e9ef47564b957f"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.15.4+0/LCIO.v2.15.4.i686-linux-gnu-cxx11.tar.gz"
[[LCIO]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "92f98572a7962683a091b89fd8ae844c26f17849"
libc = "musl"
os = "linux"

    [[LCIO.download]]
    sha256 = "5ceada09d347567b07de1868714d4b5ee0bc74f9f9781d129cc93a65acd5f05c"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.15.4+0/LCIO.v2.15.4.i686-linux-musl-cxx03.tar.gz"
[[LCIO]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4dd9fc2c6aa7c589f65b05217b00cbd317906726"
libc = "musl"
os = "linux"

    [[LCIO.download]]
    sha256 = "b3aad7420b605376b79a0834bc922892f615fccb312c1f98d182740b54a866b0"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.15.4+0/LCIO.v2.15.4.i686-linux-musl-cxx11.tar.gz"
[[LCIO]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad1c4b6987bfc279813cf2c641f9d9e2ac2f1ee4"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "64c170f787c98d06c79458ca32c6725925b1674ac58b9a01f1326a654c0621e1"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.15.4+0/LCIO.v2.15.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LCIO]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73c744685508a11fd88071949f63f5ef6102fa8b"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "bac7e61ab37fa7353e26a03db0d95d905bc2ce9b237091461060636003db1466"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.15.4+0/LCIO.v2.15.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LCIO]]
arch = "x86_64"
git-tree-sha1 = "c4603bba76bc54aea50be204a43dbebf8280175f"
os = "macos"

    [[LCIO.download]]
    sha256 = "85813c3b90b259e48265f01e5db63a59012ab536ace3a6c6fbe356cf8be03b16"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.15.4+0/LCIO.v2.15.4.x86_64-apple-darwin.tar.gz"
[[LCIO]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c2c3c57e5b69196a0f24e5b61323c487aa5135f"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "4224fa1ae05c01117307aafcec7e9da74102b4b48d04ecd550da04b170de37c3"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.15.4+0/LCIO.v2.15.4.x86_64-linux-gnu-cxx03.tar.gz"
[[LCIO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7b74d95bde685ef2d61b0c368cb20edf2e425ee"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "8d6ec1a692437f239ff9be81c43f9550be294745e556ebda092ff0db6d577a2f"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.15.4+0/LCIO.v2.15.4.x86_64-linux-gnu-cxx11.tar.gz"
[[LCIO]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "36db7c7d5519ebbbad59926a87a4bf8fc9c7873d"
libc = "musl"
os = "linux"

    [[LCIO.download]]
    sha256 = "05e722ec317db8c3d06132d7efc0e847a763c03ce67588fd93b3703ac9cabddf"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.15.4+0/LCIO.v2.15.4.x86_64-linux-musl-cxx03.tar.gz"
[[LCIO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0514e4796138e47d41b19cb5001f50c23582e1a2"
libc = "musl"
os = "linux"

    [[LCIO.download]]
    sha256 = "c75694057228464d3589f996b4562bc36e402b4f510cfaa207234c963080961d"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.15.4+0/LCIO.v2.15.4.x86_64-linux-musl-cxx11.tar.gz"
