[[LCIO]]
arch = "aarch64"
git-tree-sha1 = "b618775fcb573dcea84fbf74db9d2e601472627b"
os = "macos"

    [[LCIO.download]]
    sha256 = "0943c1fde858537c15e9e934a9a0db6a37a270f9774522d7c31be3493cc0d028"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.22.6+0/LCIO.v2.22.6.aarch64-apple-darwin.tar.gz"
[[LCIO]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b303e51763fdab28635229ab72e6aba2a4401960"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "6f8f614ad72eeeed45b8a9fcbde347066cbcc074029ce13a1fe218cc5038825a"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.22.6+0/LCIO.v2.22.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LCIO]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0bf84daa9cbbdc6e99dede1c7705a0fc49b15d3"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "32d0fd8e7e74d6194c4d87894abdf1ddc6cb6b4de990a5d4e397281315b1909e"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.22.6+0/LCIO.v2.22.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LCIO]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74150c79cfd862a20dac35aadded15dffd738828"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "ae50f3f8d2c6c06e3a13702b566eec2b24dfee0bff17bedd85dc3a50190688b2"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.22.6+0/LCIO.v2.22.6.i686-linux-gnu-cxx03.tar.gz"
[[LCIO]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbfd4087cb03d6deb7baa4920b2556a89e549ef9"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "a0b9a33374b829ddbac840c3fb9d26bee6d871e5099c877b3035af7970ddd5c0"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.22.6+0/LCIO.v2.22.6.i686-linux-gnu-cxx11.tar.gz"
[[LCIO]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3e91651abd4b0ddbf5bd346123111f45e13b99a9"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "a5cee1b2cbcba63a4dd251cc9678043d6d96f71a09c865249214391a62202d38"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.22.6+0/LCIO.v2.22.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LCIO]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f94a7f06c5b20469760a2e6171ba65c510ca0c86"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "a18b296a57edfbc723e218af5da5d30e93493e91438d6b38b4a189a2cc73ff6f"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.22.6+0/LCIO.v2.22.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LCIO]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b91e2703a73fdcaaf43bf2570f8c59fee2219a10"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "a69cac9ec14b8edb503a1f05ea667c2295528510028391021a58da1bcda1bcb7"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.22.6+0/LCIO.v2.22.6.riscv64-linux-gnu-cxx03.tar.gz"
[[LCIO]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c83b638722f4533218bf7bf56b1f8aebf8efcfca"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "028f7457bcadb414946374e863e3d02274b89c811f0a6e1ac15e0fbdbd9f8aae"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.22.6+0/LCIO.v2.22.6.riscv64-linux-gnu-cxx11.tar.gz"
[[LCIO]]
arch = "x86_64"
git-tree-sha1 = "44ebb35c2499347425501893a27b47d45eb319ed"
os = "macos"

    [[LCIO.download]]
    sha256 = "0516a26c7a28843133410c35119b5516df5821f94ed79ff6e9f636436d2c1922"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.22.6+0/LCIO.v2.22.6.x86_64-apple-darwin.tar.gz"
[[LCIO]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cc175631d7338f20b034d4bc792f27d98c086f4"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "e5a9157208d67d27dacd153ccef04534d143bc743886872f8ed7308ba025e0d5"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.22.6+0/LCIO.v2.22.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LCIO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc20842f75620c3eeb6b1ea1417d7103d9f6814f"
libc = "glibc"
os = "linux"

    [[LCIO.download]]
    sha256 = "0fb28e116907a75e99f418252f76528a7f12fb609501d455ba133ca52825a483"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_jll.jl/releases/download/LCIO-v2.22.6+0/LCIO.v2.22.6.x86_64-linux-gnu-cxx11.tar.gz"
