# Autogenerated wrapper script for LCIO_jll for x86_64-apple-darwin
export liblcio, libsio

using Zlib_jll
JLLWrappers.@generate_wrapper_header("LCIO")
JLLWrappers.@declare_library_product(liblcio, "@rpath/liblcio.2.22.dylib")
JLLWrappers.@declare_library_product(libsio, "@rpath/libsio.0.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        liblcio,
        "lib/liblcio.2.22.6.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsio,
        "lib/libsio.0.2.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
